### PR TITLE
Wrote a TP Flipping Guide

### PR DESCRIPTION
**Pull request by Scath-Enfys**
Hey, I came up with the basics of a guide. Tell me what you think! :)

### CODE REVIEW

**Comment by queicherius** [comment]
I just had a quick read through. I am gonna ignore formatting & spelling since that's pretty irrelevant, so here are my thoughts on the content per section:

> Introduction, Disclaimers, Definitions

No complaints. Looks mostly good.

> Part I: Anatomy of a Flip

I like it! The "Flipping is effectively selling your patience" statement is actually pretty smart, I chuckled at that.

> Part II: Finding profitable items

So this is where I am torn. I understand that you want to show players the (good!) tools that are out there. However, since the guide would be on gw2efficiency I would prefer it if you showed off the filters you are using while **actually using the trading post section of gw2efficiency**. All of what you are showing should be easily possible with it. I don't really want to advertise "competitors" in the guide section - hopefully this is understandable, and I don't seem like a dick. As a nice side effect this would also make a nice mini-tutorial for that (slightly more hard to understand) section of the page.

> Part III: Tips and Tricks

Short, to the point, extendible. I like it.

**Comment by Scath-Enfys** [comment]
RE: Part II, I would like to at least keep gw2tp.com in for those with slow internet connections. Efficiency is nice, but the TP tool seems to take forever and a half to load, which is why I rarely use it except for occasional investment tracking. I'll experiment some with it today, and make some edits. I won't mind removing gw2profits at all though... I prefer to keep that tool as hidden as possible lol.

**Comment by Scath-Enfys** [comment]
OK, so TP tool seems to be working much faster than I remember. There are still a few features I'd like added (list saving/HTTP-GET parameters so I can save lists in some way or another, velocity tracking / filtering), but this isn't really the place to discuss them. Still going to leave the bit about gw2tp.com in there until I have checked the load time on my normal 3Mbit/s internet (currently using guest wifi that I don't know the speed of), but things are looking good.

**Comment by Scath-Enfys** [comment]
Changed the guide as requested and added some polish too.

**Comment by queicherius** [comment]
Looks good to me! Thanks! 👍 

I'll do the same cleanup as last time and then publish it. :)

**Comment by queicherius** [comment]
[Online now.](https://gw2efficiency.com/guides/text-guides/tp-flip)

**Pull request merged**
